### ISSUE TITLE
Completely supress connection and replication errors

### ISSUE THREAD

**Issue by hansonkd** [epgsql/epgsql#232]
Hello,

I am wondering the best way to *completely* catch an error.

For example in connection I can get the error like so, however an error is still printed to the logs:

```
iex(6)> case :epgsql.connect(%{host: 'a', database: 'postgres', username: 'postgres', password: 'postgres'}) do
...(6)> 
...(6)>   {:ok, epgsql_pid} ->                                                                                 
...(6)>     IO.puts("hi")                                                                                      
...(6)>   {:error, reason} ->                                                                                  
...(6)>     IO.inspect(reason)                                                                                 
...(6)>     IO.puts("Uh Oh")                                                                                   
...(6)> end                 
iex(2)> warning: variable "epgsql_pid" is unused (if the variable is not meant to be used, prefix it with an underscore)
  iex:8

:nxdomain
Uh Oh   
iex(2)> [error] GenServer #PID<0.671.0> terminating
** (stop) :nxdomain
Last message (from #PID<0.652.0>): {:command, :epgsql_cmd_connect, %{database: 'postgres', host: 'a', password: #Function<0.89536314/0 in :epgsql_cmd_connect.hide_password/1>, username: 'postgres'}}
State: {:state, :undefined, :undefined, "", :undefined, :on_message, :undefined, {[], []}, :undefined, :undefined, :undefined, :undefined, [], [], [], :undefined, :undefined, :undefined, :undefined}
Client #PID<0.652.0> is alive

    (stdlib 3.13) gen.erl:208: :gen.do_call/4
    (stdlib 3.13) gen_server.erl:242: :gen_server.call/3
    (epgsql 4.4.0) /home/kyle/tracestate/statetrace/deps/epgsql/src/epgsql.erl:172: :epgsql.call_connect/2
    (stdlib 3.13) erl_eval.erl:680: :erl_eval.do_apply/6
    (stdlib 3.13) erl_eval.erl:273: :erl_eval.expr/5
    (elixir 1.10.3) src/elixir.erl:278: :elixir.recur_eval/3
    (elixir 1.10.3) src/elixir.erl:263: :elixir.eval_forms/3
    (iex 1.10.3) lib/iex/evaluator.ex:258: IEx.Evaluator.handle_eval/5
    (iex 1.10.3) lib/iex/evaluator.ex:239: IEx.Evaluator.do_eval/3
    (iex 1.10.3) lib/iex/evaluator.ex:217: IEx.Evaluator.eval/3
    (iex 1.10.3) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
    (iex 1.10.3) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
    (stdlib 3.13) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
:ok     
```

The same happens for replication errors, I can trap them, but they still appear as `error`s in my log. 

I would like to be able to trap these errors completely, or at least prevent them from being written to the error log. In my use case an invalid domain or missing publication is not a reason to write to the log as they are gracefully handled in the application.

**Comment by seriyps** [comment]
Hi.
You can patch epgsql to suppress this kind of error here:

https://github.com/epgsql/epgsql/blob/f8a5acc2e965c185f39150dc9d17bc75448d8a67/src/commands/epgsql_cmd_connect.erl#L83

so, replace `Reason` with `normal`. But I'm not sure making this a default is a good idea. But we can discuss / compare with similar software.

**Comment by seriyps** [comment]
Regarding replication errors: can you post some examples?
